remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3


permalink:   /:categories/:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  
page_width: 600px
